# Generated by Django 5.1.4 on 2025-01-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('basic_worker', 'Basic Worker'), ('admin', 'Admin')], default='basic_worker', max_length=20),
        ),
    ]
