# Generated by Django 5.1.4 on 2025-01-16 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('machine_type', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('fleet_number', models.CharField(max_length=30)),
                ('oem', models.CharField(max_length=255)),
                ('year_of_manufacture', models.DateField()),
                ('mine', models.CharField(max_length=50)),
                ('last_seen', models.DateField()),
                ('mileage', models.IntegerField()),
                ('operating_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('total_number_of_machines', models.IntegerField()),
                ('number_of_operators', models.IntegerField()),
                ('shift_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='keyPerformanceIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_per_shift', models.IntegerField()),
                ('time_per_shift', models.IntegerField()),
                ('machine_type', models.CharField(max_length=255)),
                ('tonnage_per_shift', models.IntegerField()),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.mine')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=15)),
                ('employee_number', models.CharField(max_length=15)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.mine')),
            ],
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_number', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.machine')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.mine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.operator')),
            ],
        ),
        migrations.CreateModel(
            name='opsum_per_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=1992)),
                ('distance_travelled', models.IntegerField()),
                ('tonnage', models.CharField(max_length=255)),
                ('fuel_consumed', models.IntegerField()),
                ('no_of_loads', models.IntegerField()),
                ('operating_hours', models.IntegerField()),
                ('idle_hours', models.IntegerField()),
                ('engine_hours', models.IntegerField()),
                ('transmission_hours', models.IntegerField()),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.mine')),
                ('shift_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.shift')),
            ],
        ),
    ]
