# Generated by Django 5.1.4 on 2025-01-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsum_per_shift',
            name='shift_number',
            field=models.IntegerField(),
        ),
    ]
