# Generated by Django 5.1.4 on 2025-01-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0002_alter_opsum_per_shift_shift_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsum_per_shift',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machinesList.machine'),
        ),
        migrations.AddField(
            model_name='opsum_per_shift',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machinesList.operator'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='employee_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
