# Generated by Django 5.1.4 on 2025-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0003_opsum_per_shift_machine_opsum_per_shift_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyperformanceindicators',
            name='fuel_per_shift',
            field=models.IntegerField(default=200),
        ),
    ]
