# Generated by Django 5.1.4 on 2025-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0005_sensor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='Transmission_oil',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
