# Generated by Django 5.1.4 on 2025-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0007_sensor_data_unique_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsum_per_shift',
            name='tonnage',
            field=models.IntegerField(max_length=255),
        ),
    ]
