# Generated by Django 5.1.4 on 2025-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0010_alter_opsum_per_shift_tonnage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor_data',
            name='unique_fields',
        ),
        migrations.AddConstraint(
            model_name='sensor_data',
            constraint=models.UniqueConstraint(fields=('date', 'shift_number', 'mine', 'machine'), name='unique_fields'),
        ),
    ]
