# Generated by Django 5.1.4 on 2025-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0012_remove_sensor_data_unique_fields_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opsum_per_shift',
            constraint=models.UniqueConstraint(fields=('date', 'shift_number', 'mine', 'machine'), name='unique_machine_shift_date_mine_opsum'),
        ),
    ]
