# Generated by Django 5.1.4 on 2025-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0013_opsum_per_shift_unique_machine_shift_date_mine_opsum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor_data',
            name='unique_machine_shift_date_mine',
        ),
        migrations.AddConstraint(
            model_name='sensor_data',
            constraint=models.UniqueConstraint(fields=('date', 'shift_number', 'mine', 'machine'), name='unique_fields'),
        ),
    ]
