# Generated by Django 5.1.4 on 2025-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0014_remove_sensor_data_unique_machine_shift_date_mine_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sensor_data',
            name='unique_fields',
        ),
        migrations.AddConstraint(
            model_name='sensor_data',
            constraint=models.UniqueConstraint(fields=('date', 'shift_number', 'mine', 'machine'), name='unique_sensor_data'),
        ),
    ]
