# Generated by Django 5.1.4 on 2025-04-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0016_convert_mine_to_foreign_key'),
    ]

    operations = [
    ]
