# Generated by Django 5.1.4 on 2025-04-27 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinesList', '0017_convert_mine_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='mine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machinesList.mine', to_field='name'),
        ),
    ]
